name: Build and Package Application

on:
  push:
    branches:
      - main_no_trans
  pull_request:
    branches:
      - main_no_trans

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build application
      run: |
        pyinstaller MyApp.spec --noconfirm
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BP-writing-tool-windows
        path: dist/
        retention-days: 30
        
    - name: Create release info
      run: |
        echo "Build completed successfully!"
        echo "Executable available in dist/ folder"
        echo "Download the artifact 'BP-writing-tool-windows' to get the built application" 